from pydantic import BaseModel, Field
from typing import Optional, List


class GeneratedFile(BaseModel):
    file_path: str = Field(description="Complete path to the file")
    file_name: str = Field(description="Name of the generated Python file")
    file_content: str = Field(description="Complete code for the file")
    file_inputs: List[str] = Field(
        description=(
            "Concrete stdin values needed to run this program to completion via subprocess, "
            "in the exact order the program's input() calls will consume them. "
            "If the code contains ANY input() calls — including menu loops, REPLs, or "
            "prompts — you MUST provide a full realistic sequence of values that exercises "
            "the program (e.g. select a menu option, provide required data, then an exit "
            "command if the loop needs one to terminate). Only leave this empty if the code "
            "contains zero input() calls. Do not skip this because the program 'is interactive' "
            "— interactive programs still need scripted stdin to be validated."
        )
    )
    file_inputs_reason: str = Field(description="Reason for the input of each line of the file. If inputs not provided, give the reason for not providing it")


class Errors(BaseModel):
    success: bool = Field(description="Whether the execution was successful")
    error_summary: str = Field(description="Summary of the error")
    stdout: str = Field(description="The stdout of the execution")
    stderr: str = Field(description="The stderr of the execution")


class CoderDocumentation(BaseModel):
    attempt: int = Field(description="Current number of attempt")
    errors: List[Errors] = Field(default=None, description="List of errors occurred. Do not populate this in the initial stage. Only populate this when you have got errors")
    stage: str = Field(description="Stage of the code like initial stage, attempt 1, attempt 2, etc")
    goal: str = Field(description="The end goal that is required to be achieved")
    actions: List[str] = Field(description="List of actions taken in this step")
    decision: List[str] = Field(description="Key decisions taken in this step along with reasoning")
    expected_outcome: str = Field(description="Expected outcome after this step")


class ProjectOutput(BaseModel):
    project_name: str = Field(description="Folder name for the project")
    project_directory: str = Field(description="Complete path to the folder where the project was generated")
    description: str = Field(description="Short project description")
    file: GeneratedFile
    coder_documentation: CoderDocumentation = Field(description="Documentation of the coder")


class ExecutorResult(BaseModel):
    task: str  # original task description
    code: str  # current generated code (from coder)
    file_path: str  # path where writer saved the file

    stdout: str  # captured stdout from execution
    stderr: str  # captured stderr from execution
    exit_code: int  # process exit code
    success: bool  # whether execution succeeded
    error_summary: Optional[str] = None  # last traceback line, for quick context

    retry_count: int = Field(default=0)  # number of retry attempts so far


class KnowledgeState(BaseModel):
    task: str
    success: bool = Field(description="Whether the execution was successful")
    attempts: int = Field(description="Number of total attempts")
    design_decisions: List[str] = Field(description="Design decisions that helped in success of the code")
    lesson: List[str] = Field(description="Lessons learnt while developing the project which would help in later projects")



# Main Agent State
class State(BaseModel):
    user_input: str = Field(
        description="Original user request."
    )

    project: ProjectOutput | None = Field(
        default=None,
        description="Project generated by the planner/coder."
    )

    executor: ExecutorResult | None = Field(
        default=None,
        description="Result of executing the generated project."
    )