from pydantic import BaseModel, Field
from typing import Optional


class GeneratedFile(BaseModel):
    file_path: str = Field(description="Complete path to the file")
    file_name: str = Field(description="Name of the generated Python file")
    file_content: str = Field(description="Complete code for the file")


class ProjectOutput(BaseModel):
    project_name: str = Field(description="Folder name for the project")
    project_directory: str = Field(description="Complete path to the folder where the project was generated")
    description: str = Field(description="Short project description")
    file: GeneratedFile


class ExecutorResult(BaseModel):
    task: str  # original task description
    code: str  # current generated code (from coder)
    file_path: str  # path where writer saved the file

    stdout: str  # captured stdout from execution
    stderr: str  # captured stderr from execution
    exit_code: int  # process exit code
    success: bool  # whether execution succeeded
    error_summary: Optional[str] = None  # last traceback line, for quick context

    retry_count: int = Field(default=0)  # number of retry attempts so far


class State(BaseModel):
    user_input: str = Field(
        description="Original user request."
    )

    project: ProjectOutput | None = Field(
        default=None,
        description="Project generated by the planner/coder."
    )

    executor: ExecutorResult | None = Field(
        default=None,
        description="Result of executing the generated project."
    )